# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/SSD_Test.xdc

# Block Designs: bd/ALU/ALU.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU || ORIG_REF_NAME==ALU} -quiet] -quiet

# IP: bd/ALU/ip/ALU_microblaze_0_0_1/ALU_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_microblaze_0_0 || ORIG_REF_NAME==ALU_microblaze_0_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_dlmb_v10_0_1/ALU_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_dlmb_v10_0 || ORIG_REF_NAME==ALU_dlmb_v10_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_ilmb_v10_0_1/ALU_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_ilmb_v10_0 || ORIG_REF_NAME==ALU_ilmb_v10_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_dlmb_bram_if_cntlr_0_1/ALU_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==ALU_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_ilmb_bram_if_cntlr_0_1/ALU_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==ALU_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_lmb_bram_0_1/ALU_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_lmb_bram_0 || ORIG_REF_NAME==ALU_lmb_bram_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_xbar_0_1/ALU_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_xbar_0 || ORIG_REF_NAME==ALU_xbar_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_microblaze_0_axi_periph_0_1/ALU_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_microblaze_0_axi_periph_0 || ORIG_REF_NAME==ALU_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_mdm_1_0_1/ALU_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_mdm_1_0 || ORIG_REF_NAME==ALU_mdm_1_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_clk_wiz_1_0_1/ALU_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_clk_wiz_1_0 || ORIG_REF_NAME==ALU_clk_wiz_1_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_rst_clk_wiz_1_100M_0_1/ALU_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==ALU_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_axi_gpio_0_0_1/ALU_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_axi_gpio_0_0 || ORIG_REF_NAME==ALU_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ALU/ip/ALU_axi_uartlite_0_0_1/ALU_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ALU_axi_uartlite_0_0 || ORIG_REF_NAME==ALU_axi_uartlite_0_0} -quiet] -quiet

# XDC: bd/ALU/ALU_ooc.xdc
